### ISSUE TITLE
The `Process` class is incompatible again with older Symfony versions

### ISSUE THREAD

**Issue by markvds** [sebastianfeldmann/cli#9]
I left a comment on the commit: https://github.com/sebastianfeldmann/cli/commit/8fbc7b32066cd1c4ad2ca80ef0e258444bc59bf8#r40145084

I think the change was because some code inspection noticed that the first argument of the constructor needs to be an array. But the whole purpose of the alternative way to instantiate the `Process` object is to support older Symfony versions in which the argument is untyped.

**Comment by sebastianfeldmann** [comment]
Yes, seen the comment, I think you are right @peter279k changed this unintentionally with some automated functionality

**Comment by markvds** [comment]
Thanks for the superfast fix! I can confirm Captain Hook works again for Magento 2 :+1:

**Comment by sebastianfeldmann** [comment]
My pleasure sorry for breaking things in the first place ;)

**Comment by markvds** [comment]
Forgiven! And thank ye fer yer wonderful Captain Hook!
